const router = require('express').Router();
const controller = require('./usuarios.controller');
const auth = require('../../middlewares/auth.middleware');
const role = require('../../middlewares/role.middleware');
const validate = require('../../middlewares/validate.middleware');
const schemas = require('./usuarios.validation');
router.use(auth, role('ADMINISTRADOR'));
router.get('/', controller.listar);
router.post('/', validate(schemas.crearUsuarioSchema), controller.crear);
router.put('/:id/rol', validate(schemas.cambiarRolSchema), controller.cambiarRol);
router.put('/:id', validate(schemas.actualizarUsuarioSchema), controller.actualizar);
router.delete('/:id', controller.eliminar);
module.exports = router;
